# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('token', models.CharField(max_length=1048, unique=True)),
                ('start', models.DateTimeField(verbose_name='when to start')),
                ('stop', models.DateTimeField(verbose_name='when to stop')),
            ],
        ),
    ]
