# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-28 23:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('pathfeets', '0002_position'),
    ]

    operations = [
        migrations.CreateModel(
            name='PlannedPosition',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('timestamp', models.DateTimeField(verbose_name='time at location')),
                ('longitude', models.FloatField(default=0)),
                ('latitude', models.FloatField(default=0)),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pathfeets.Event')),
            ],
        ),
    ]
